// <auto-generated />
using System;
using ATS_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATS_1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20190714143354_init5")]
    partial class init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATS_1.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity");

                    b.Property<DateTime>("ActivityDatetime");

                    b.Property<int>("ApplicantID");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("ATS_1.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApplicationDate");

                    b.Property<string>("CVAttachment");

                    b.Property<string>("CareerLevel");

                    b.Property<string>("Currentposition");

                    b.Property<string>("Degree");

                    b.Property<int?>("Devexperience");

                    b.Property<string>("Email");

                    b.Property<string>("EnglishSkills");

                    b.Property<double?>("ExamScore");

                    b.Property<int>("ExpectedSalary");

                    b.Property<double?>("GPA1");

                    b.Property<double?>("GPA2");

                    b.Property<string>("Howdidyoufindus");

                    b.Property<DateTime?>("InterviewDate");

                    b.Property<string>("JoinDate");

                    b.Property<string>("LastUdateLog");

                    b.Property<string>("Major");

                    b.Property<string>("Name");

                    b.Property<string>("Nationality");

                    b.Property<string>("Notes");

                    b.Property<string>("OtherUniversity");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Status");

                    b.Property<int?>("TeamLeaderExperience");

                    b.Property<string>("Technologies");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("ToCallDate");

                    b.Property<string>("University");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ATS_1.Models.ApplicantStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicantId");

                    b.Property<string>("Status");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("ApplicantStatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
